# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9963f75d23ccb2f8fcb1835044222cecad5eeba25383974101ef07465d8893cbd201697472ff6774d534d8f3bd0b4eccd61e0958e04697e884cf5d86817f580

test:
  secret_key_base: 4363ff7a24c4917ad0fc1ae9e9c75546069bf222d699513d0c050dc576c75d8d2062fa7ab73099d60b9fbb626573e66a58cbae3cd99ec1e4b073367bc0f65ac7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
